# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: clickhouse
version: 1.0.0
readme: README.md
authors:
  - Ansible ClickHouse community
description: ClickHouse collection for Ansible
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - database
  - clickhouse
# documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
repository: https://github.com/ansible-collections/community.clickhouse
homepage: https://github.com/ansible-collections/community.clickhouse
issues: https://github.com/ansible-collections/community.clickhouse/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
